[package]
name = "yggy"
version = "0.0.0-alpha.1"
edition = "2018"
authors = ["sunny-g <sunny.gonna@gmail.com>"]
description = "An end-to-end encrypted IPv6 mesh network"
readme = "README.md"
repository = "https://github.com/datalove-app/yggy"
keywords = ["cryptography", "networking", "p2p"]
categories = ["cryptography"]
license = "LGPL-3.0" # TODO

[lib]
name = "yggy"
path = "src/lib.rs"

# TODO restrict binary building to linux/mac/windows
[[bin]]
name = "yggyd"
path = "bin/yggyd/main.rs"

[[bin]]
name = "yggyctl"
path = "bin/yggyctl/main.rs"

[dependencies]
actix = "0.9"
actix-net = "0.2"
anyhow = "1.0"
async-trait = "0.1"
boringtun = "0.3"
derive_more = "0.99"
digest = "0.8.1"
ed25519-dalek = { version = "0.9", features = ["serde"] }
lazy_static = "1.4"
rand = "0.6"
serde = { version = "1.0", features = ["derive"] }
sha2 = { version = "0.8.1", default-features = false }
thiserror = "1.0"
tokio = { version = "0.2", features = ["full"] }

[features]
default = ["std", "u64_backend"]
# re-exports of various dependency features
std = ["ed25519-dalek/std", "sha2/std"]
alloc = ["ed25519-dalek/alloc"]
nightly = ["ed25519-dalek/nightly"]
asm = ["ed25519-dalek/asm", "sha2/asm"]
yolocrypto = ["ed25519-dalek/yolocrypto"]
u64_backend = ["ed25519-dalek/u64_backend"]
u32_backend = ["ed25519-dalek/u32_backend"]
avx2_backend = ["ed25519-dalek/avx2_backend"]
