[package]
name = "yggy"
version = "0.0.0-alpha.1"
edition = "2018"
authors = ["sunny-g <sunny.gonna@gmail.com>"]
description = "An end-to-end encrypted IPv6 mesh network"
readme = "README.md"
repository = "https://github.com/datalove-app/yggy"
keywords = ["cryptography", "networking", "p2p"]
categories = ["cryptography"]
license = "LGPL-3.0" # TODO

[lib]
name = "yggy"
path = "src/lib.rs"

# TODO restrict binary building to linux/mac/windows
[[bin]]
name = "yggyd"
path = "bin/yggyd/main.rs"

[[bin]]
name = "yggyctl"
path = "bin/yggyctl/main.rs"

[dependencies]
actix = "0.9"
anyhow = "1.0"
async-trait = "0.1"
boringtun = "0.3"
derive_more = "0.99"
ed25519-dalek = { version = "0.9", features = ["serde"] }
rand = "0.6"
serde = { version = "1.0", features = ["derive"] }
sodiumoxide = { version = "0.2", default-features = false, features = ["serde"] }
thiserror = "1.0"
tokio = { version = "0.2", features = ["full"] }

[features]
default = ["std", "u64_backend"]
# re-exports of ed25519-dalek features
std = ["ed25519-dalek/std", "sodiumoxide/std"]
alloc = ["ed25519-dalek/alloc"]
nightly = ["ed25519-dalek/nightly"]
asm = ["ed25519-dalek/asm"]
yolocrypto = ["ed25519-dalek/yolocrypto"]
u64_backend = ["ed25519-dalek/u64_backend"]
u32_backend = ["ed25519-dalek/u32_backend"]
avx2_backend = ["ed25519-dalek/avx2_backend"]
