[package]
name = "yggy"
version = "0.0.0"
authors = ["sunny-g <sunny.gonna@gmail.com>"]
edition = "2018"

[lib]
name = "yggy"
path = "src/lib.rs"

#[[bin]]
#name = "yggy"
#path = "src/bin.rs"
#
#[[bin]]
#name = "yggyctl"
#path = "src/ctl.rs"

[dependencies]
anyhow = "1.0"
boringtun = "0.3"
derive_more = "0.99"
libp2p = "0.18"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"

[features]
default = []
